feat: more `Book` schema properties
timharek/openlibrary pull request #2
Opened 2024-10-06 01:24 UTC by shayypy

This PR just adds a few optional properties missing from `Book`. Examples of each can be found here: https://openlibrary.org/books/OL7353617M.json (in this case, `/books/:id` was redirected from `/works/:id`, so the same should apply to responses from `getRequest`).

I also modified `AuthorObj` to accept a value of just `{ key: "/authors/..." }`, which is also found in the above example. This would be a breaking change but I decided to transform the value to be compatible with the prior schema so it should be fine for applications that depend on that.

Some other observations I had, but did not address, include:
- The `Date` schema shadows javascript's `Date`, which my linter is not fond of.
- `getByISBN`'s omission of a leading slash when assigning `pathname` (I guess this works fine, but it seems weird)
- Every query function assigns values to the same `API_URL`, which seems like it could cause problems since there would be residue for instances like `book.search`, which assigns a query parameter, but no other functions overwrite it. I think it would be better practice to create a new URL within each function like so: `new URL('/works/...', API_URL)`
- `mod.ts` does not export any schemas or types, which makes it challenging to refer to types from this package or extend schemas
- The schemas are not utilizing Zod's [passthrough](https://zod.dev/?id=passthrough), which of course means unknown keys like the ones I added are completely inaccessible to the user. Personally I think users should have some way to access this data even if it's untyped (for example, while waiting for PR approval lol).

2024-10-06 16:22 UTC, timharek requested changes
Thank you! This is a great addition.

I added two comments for props that should be optional, you can see that with `deno task test`.

2024-10-06 16:22 UTC, timharek commented on src/schemas.ts
> +  contributions: z.array(z.string()),
```suggestion
  contributions: z.array(z.string()).optional(),
```

I see that this prop doesn't always appear.

2024-10-06 16:22 UTC, timharek commented on src/schemas.ts
> +  works: z.array(z.object({ key })),
```suggestion
  works: z.array(z.object({ key })).optional(),
```
I also see that this prop doesn't always appear.

2024-10-06 16:30 UTC, shayypy commented
Thanks, I forgot to mark those as optional 👍

2024-10-06 16:34 UTC, timharek commented
> The Date schema shadows javascript's Date, which my linter is not fond of.

Do you mean that the const name interfers with your linter?

> `getByISBN`'s omission of a leading slash when assigning pathname (I guess this works fine, but it seems weird)

Good catch, fixing it now!

> Every query function assigns values to the same API_URL, which seems like it could cause problems since there would be residue for instances like book.search, which assigns a query parameter, but no other functions overwrite it. I think it would be better practice to create a new URL within each function like so: new URL('/works/...', API_URL)

Good suggestion, refactoring now.

> `mod.ts` does not export any schemas or types, which makes it challenging to refer to types from this package or extend schemas

 A new PR is much appreicated, but I can have a look as well.

> The schemas are not utilizing Zod's [passthrough](https://zod.dev/?id=passthrough), which of course means unknown keys like the ones I added are completely inaccessible to the user. Personally I think users should have some way to access this data even if it's untyped (for example, while waiting for PR approval lol).

I wasn't aware of this feature, I added this to all the parsing now!

2024-10-06 16:37 UTC, merged

2024-10-06 17:57 UTC, shayypy commented
> Do you mean that the const name interfers with your linter?

Yes, it's not particularly important since the vanilla `Date` is not used in this file anyway, but Biome pointed it out to me and I thought it was worth noting.
<img width="733" alt="image" src="https://github.com/user-attachments/assets/21d835cd-eaff-4553-a051-6a472c743498">

2024-10-07 06:46 UTC, timharek commented
> Yes, it's not particularly important since the vanilla `Date` is not used in this file anyway, but Biome pointed it out to me and I thought it was worth noting. 

Is it fixed by changing the name? I use Deno's LSP, so I don't get this error/warning. I'm open for PR if you want to change it :)